# Generated by Django 2.2 on 2020-03-26 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200324_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 26, 8, 40, 4, 874817, tzinfo=utc)),
        ),
    ]
