# Generated by Django 2.2 on 2020-03-26 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200326_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 26, 13, 11, 3, 945060, tzinfo=utc)),
        ),
    ]
