# Generated by Django 2.2 on 2020-03-26 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200326_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 3, 26, 13, 11, 3, 947066, tzinfo=utc))),
            ],
        ),
    ]
